package com.kujtimhoxha.test;

/**
 * MyTest.
 *
 * @author Kujtim Hoxha (kujtimii.h@gmail.com)
 * @version $Id$
 * @since 0.1
 */
public class MyTest {
    /**
     *[todo] $ This is an autogenerated issue [issue=#1] $
     * #/
     * # My Issue
     * This issue is posted because this project uses [todo-issue-plugin](https://github.com/kujtimiihoxha/todo-issue)
     * #/
     * ~kujtimiihoxha~
     * %bug,dev,testissue%
     */
    private static final String myString="Testing todo-issue";

    public static void myMethod(){
        /**
         *[todo]  $ This is an issue inside of a method [issue=#2]  $
         * #/
         * # Method issue
         * The issue can be everywhere, also assignee and labels are not
         * required
         * #/
         */
        System.out.println("MyTest.myString = " + MyTest.myString);
    }
}
